### ISSUE TITLE
Material integration from other mods

### ISSUE THREAD

**Issue by Katalliaan** [Katalliaan/Rubedo#55]
Just putting this here as a reference to the other materials that will be in the pack

# Brass (FSP)
Normal stats:
* mining level 2
* 191 durability
* 7.0F speed
* 2.5F attack
* 14 enchantability

# Gilded (FSP)
Normal stats:
* mining level 2
* 250 durability
* 6.0F speed
* 2.0F attack
* 22 enchantability

# Thaumium (Thaumcraft)
Normal stats:
* mining level 3
* 400 durability
* 7.0F speed
* 2.0F attack
* 22 enchantability
* Source: iron ingot + praecantitio essentia in crucible (cauldron smacked with wand). Very easy to get, might need to be brought down to iron's mining level

# Voidmetal (Thaumcraft)
Normal stats:
* mining level 4
* 150 durability
* 8.0F speed
* 3.0F attack
* 10 enchantability
* self-repairing
* Warping I (gives temporary warp to user)
* Sword appears to give 80 seconds of Weakness I to any targets hit
* Source: void seeds + metallum essentia in crucible. Voidmetal's fairly high up - it's gated on a warp event, which means a lot of research beforehand

**Comment by SimonMeskens** [comment]
I added Thaumium, Brass and Gilded. Still need to add the localization strings

**Comment by SimonMeskens** [comment]
Need to add Coral from OceanCraft

**Comment by SimonMeskens** [comment]
Coral is in
