### ISSUE TITLE
Make the bowl stay in the crafting grid when crafting gravel

### ISSUE THREAD

**Issue by SimonMeskens** [Katalliaan/Rubedo#58]

**Comment by Katalliaan** [comment]
This'll need a custom crafting handler. See below for example:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/1425630-how-to-keep-an-item-in-the-crafting-table?comment=7

**Comment by SimonMeskens** [comment]
The code should be very light and fail early, as a crafting handler runs every time anything is crafted. Very easy to slow the game down by having stuff like that.
