### ISSUE TITLE
Sword of the Fallen Soldier from Gravestone displays Missing Texture

### ISSUE THREAD

**Issue by Kaitocain** [Katalliaan/Rubedo#61]
The texture uses the same texture that the Wooden Sword uses, and because the wooden sword is missing a texture, so too is the Sword of the Fallen Soldier. This should be fixed with a rendition of the original texture of the Wooden Sword. *This may also apply to the other original sword styles as well.

**Comment by SimonMeskens** [comment]
Textures are registered first, Gravestone assumes textures from vanilla are already registered, which in this case, they aren't. This is not an integration bug and needs to be fixed for Rubedo proper. I'll add registrations for all the textures that don't get initialized due to my changes.

**Comment by SimonMeskens** [comment]
Was fixed in 4d2a80399674d41029c879265939831aeb6d6513
