### ISSUE TITLE
EB dirt doesn't convert to rice paddies

### ISSUE THREAD

**Issue by SimonMeskens** [Katalliaan/Rubedo#63]

**Comment by Katalliaan** [comment]
Relevant code from GrowthCraft:
https://github.com/Alatyami/Growthcraft-1.7/blob/da29b61f22fe950052fe2e5aa45d4ba1ec31d90a/src/java/growthcraft/core/event/PlayerInteractEventPaddy.java

**Comment by SimonMeskens** [comment]
will not fix
