### ISSUE TITLE
WAILA light level tooltip issue

### ISSUE THREAD

**Issue by woggy** [Katalliaan/Rubedo#68]
(spotted in pack 1.3.0rc2)

When holding one of the Rubedo tools and looking at some blocks, the WAILA tooltip shows, instead of the light level, an <ERROR> placeholder.

Providing an exhaustive enumeration is beyond my capabilities at the moment, but observed in my base:

Working properly: Dirt, Grass Block, (EB) Stone/Stone Bricks, Chest
Error: Crafting table, Furnace, Bed, (EB) Wood Planks, Wheat, Glass Pane, Torch

![2015-10-29_19 11 39](https://cloud.githubusercontent.com/assets/3821254/10836254/1b330a62-7e71-11e5-915e-84f26f6c4a98.png)

**Comment by SimonMeskens** [comment]
I've seen these too, yeah. Not sure if I'll be able to fix that though.

**Comment by SimonMeskens** [comment]
I'm thinking this might be due to our tools not implementing a certain method correctly that it's calling, need to check WAWLA source

**Comment by SimonMeskens** [comment]
fixed now
