### ISSUE TITLE
Repairing tool removes enchants

### ISSUE THREAD

**Issue by Katalliaan** [Katalliaan/Rubedo#74]
https://github.com/Katalliaan/Rubedo/blob/8d5cdf27f7e12bf89c7138fcbcaab23fdb352511/src/main/java/rubedo/items/tools/recipes/ToolRepairRecipes.java#L103

Would it be possible to adjust the above to only remove the enchant if you are changing the material?

**Comment by SimonMeskens** [comment]
For future reference, you need to repair tools in the anvil to keep the enchants
