### ISSUE TITLE
Thaumcraft aspects

### ISSUE THREAD

**Issue by SimonMeskens** [Katalliaan/Rubedo#80]
Rubedo tools have some pretty nonsensical aspects, due to clay being counted for terra, but them not having instrumentum because they don't overwrite ItemTool and such.

**Comment by Katalliaan** [comment]
As of 4cf961e, all usable tool heads should have their aspects in place (hot and unrefined don't, as I was unsure what to give those). It doesn't seem possible to use NBT data for aspects, though, so our tools can't have their aspects properly assigned.

**Comment by Katalliaan** [comment]
Closing this issue, as the only NBT data that's used in calculating aspects is all hardcoded in Thaumcraft itself.
