### ISSUE TITLE
Thaumium tools as recipe items

### ISSUE THREAD

**Issue by SimonMeskens** [Katalliaan/Rubedo#81]
Diabolist forks require a thaumium tool for infusion, needs to be added.

**Comment by SimonMeskens** [comment]
Other items:

Shovel of the Purifier (Forbidden Magic)
Chameleon Shovel (Forbidden Magic)
Thaumic stone extruder (witching gadgets)
Pickaxe of Distortion (Forbidden Magic)
Chameleon Pickaxe (Forbidden Magic)
Axe of the Skulltaker (Forbidden Magic)
Chameleon Axe (Forbidden Magic)
Cursed Spirit's Blade (Thaumic Tinkerer)
Chameleon Sword (Forbidden Magic)
Diabolist Fork (Forbidden Magic)

**Comment by SimonMeskens** [comment]
a dynamic way might be necessary indeed

**Comment by Katalliaan** [comment]
This was implemented in ede2a7a and is in for the current pack version.
